ROOT=../..

include $(ROOT)/common.mk


O =  \
aliType.o \
bits.o \
chain.o \
chainBlock.o \
common.o \
dlist.o \
dnaseq.o \
dnautil.o \
dystring.o \
errabort.o \
fa.o \
ffAli.o \
ffAliHelp.o \
ffScore.o \
fuzzyFind.o \
genoFind.o \
gfBlatLib.o \
gfClientLib.o \
gfInternal.o \
gfOut.o \
hash.o \
linefile.o \
localmem.o \
memalloc.o \
obscure.o \
options.o \
osunix.o \
pipeline.o \
psl.o \
supStitch.o \
trans3.o \
twoBit.o \
verbose.o \
gfOutputResult.o \
gfResult.o \
gfDb.o \
mlatParams.o \
mlatPriv.o \

#nib.o \
#kxTok.o \
#bPlusTree.o \
#servcl.o \

all: $(O)
	

clean:
	rm -f *.{o,gcov,gcda,gcno,log}

