ROOT=../..

include $(ROOT)/common.mk


O =  \
gfNet.o \
log.o \
net.o \
internet.o \
cheapcgi.o \
https.o \
mime.o \
portimpl.o \
servcl.o \
intExp.o \
kxTok.o \
gfBlatNetLib.o \

all: $(O)
	

clean:
	rm -f *.{o,gcov,gcda,gcno,log}

