ROOT=../..

include $(ROOT)/common.mk

O =  \
axt.o \
bandExt.o \
base64.o \
binRange.o \
blastOut.o \
ffSeedExtend.o \
filePath.o \
maf.o \
mafFromAxt.o \
ooc.o \
patSpace.o \
rangeTree.o \
rbTree.o \
repMask.o \
sqlList.o \
sqlNum.o \
wildcmp.o \

#mime.o \
#https.o \
#internet.o \
#net.o \
#intExp.o \
#udc.o \
#cheapcgi.o \
#servBrcMcw.o \
#servCrunx.o \
#servcis.o \
#servmsII.o \
#servpws.o \
#portimpl.o \


all: $(O)
	

clean:
	rm -f *.{o,gcov,gcda,gcno,log}

