ROOT=../..

include $(ROOT)/common.mk

O =  \
axt.o \
bandExt.o \
base64.o \
binRange.o \
blastOut.o \
cheapcgi.o \
ffSeedExtend.o \
filePath.o \
https.o \
intExp.o \
internet.o \
maf.o \
mafFromAxt.o \
mime.o \
net.o \
ooc.o \
patSpace.o \
portimpl.o \
rangeTree.o \
rbTree.o \
repMask.o \
servBrcMcw.o \
servCrunx.o \
servcis.o \
servmsII.o \
servpws.o \
sqlList.o \
sqlNum.o \
udc.o \
wildcmp.o \


all: $(O)
	

